# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMoya' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestMoya
pod 'Moya', '13.0.0'
end
